// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using YMKB.UI.APIs.AIChat.Chat;
namespace YMKB.UI.APIs.AIChat
{
    /// <summary>
    /// Builds and executes requests for operations under \AIChat
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AIChatRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The chat property</summary>
        public global::YMKB.UI.APIs.AIChat.Chat.ChatRequestBuilder Chat
        {
            get => new global::YMKB.UI.APIs.AIChat.Chat.ChatRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::YMKB.UI.APIs.AIChat.AIChatRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AIChatRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/AIChat", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::YMKB.UI.APIs.AIChat.AIChatRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AIChatRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/AIChat", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
