// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using YMKB.UI.APIs.AIModels;
using YMKB.UI.APIs.Auth;
using YMKB.UI.APIs.FileManagement;
using YMKB.UI.APIs.KbApps;
using YMKB.UI.APIs.KbDocFiles;
using YMKB.UI.APIs.KnowledgeDbs;
using YMKB.UI.APIs.Products;
using YMKB.UI.APIs.WeatherForecast;
namespace YMKB.UI.APIs
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiClient : BaseRequestBuilder
    {
        /// <summary>The AIModels property</summary>
        public global::YMKB.UI.APIs.AIModels.AIModelsRequestBuilder AIModels
        {
            get => new global::YMKB.UI.APIs.AIModels.AIModelsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Auth property</summary>
        public global::YMKB.UI.APIs.Auth.AuthRequestBuilder Auth
        {
            get => new global::YMKB.UI.APIs.Auth.AuthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The fileManagement property</summary>
        public global::YMKB.UI.APIs.FileManagement.FileManagementRequestBuilder FileManagement
        {
            get => new global::YMKB.UI.APIs.FileManagement.FileManagementRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The KbApps property</summary>
        public global::YMKB.UI.APIs.KbApps.KbAppsRequestBuilder KbApps
        {
            get => new global::YMKB.UI.APIs.KbApps.KbAppsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The KbDocFiles property</summary>
        public global::YMKB.UI.APIs.KbDocFiles.KbDocFilesRequestBuilder KbDocFiles
        {
            get => new global::YMKB.UI.APIs.KbDocFiles.KbDocFilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The KnowledgeDbs property</summary>
        public global::YMKB.UI.APIs.KnowledgeDbs.KnowledgeDbsRequestBuilder KnowledgeDbs
        {
            get => new global::YMKB.UI.APIs.KnowledgeDbs.KnowledgeDbsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The products property</summary>
        public global::YMKB.UI.APIs.Products.ProductsRequestBuilder Products
        {
            get => new global::YMKB.UI.APIs.Products.ProductsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The WeatherForecast property</summary>
        public global::YMKB.UI.APIs.WeatherForecast.WeatherForecastRequestBuilder WeatherForecast
        {
            get => new global::YMKB.UI.APIs.WeatherForecast.WeatherForecastRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::YMKB.UI.APIs.ApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "http://localhost:5045";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
    }
}
#pragma warning restore CS0618
