// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace YMKB.UI.APIs.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class KbDocFileDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The created property</summary>
        public DateTimeOffset? Created { get; set; }
        /// <summary>The dataCount property</summary>
        public int? DataCount { get; set; }
        /// <summary>The fileName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FileName { get; set; }
#nullable restore
#else
        public string FileName { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The kbId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? KbId { get; set; }
#nullable restore
#else
        public string KbId { get; set; }
#endif
        /// <summary>The segmentPattern property</summary>
        public global::YMKB.UI.APIs.Models.SegmentPattern? SegmentPattern { get; set; }
        /// <summary>The size property</summary>
        public long? Size { get; set; }
        /// <summary>The status property</summary>
        public global::YMKB.UI.APIs.Models.NullableOfQuantizationState? Status { get; set; }
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>The url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::YMKB.UI.APIs.Models.KbDocFileDto"/> and sets the default values.
        /// </summary>
        public KbDocFileDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::YMKB.UI.APIs.Models.KbDocFileDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::YMKB.UI.APIs.Models.KbDocFileDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::YMKB.UI.APIs.Models.KbDocFileDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created", n => { Created = n.GetDateTimeOffsetValue(); } },
                { "dataCount", n => { DataCount = n.GetIntValue(); } },
                { "fileName", n => { FileName = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "kbId", n => { KbId = n.GetStringValue(); } },
                { "segmentPattern", n => { SegmentPattern = n.GetEnumValue<global::YMKB.UI.APIs.Models.SegmentPattern>(); } },
                { "size", n => { Size = n.GetLongValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::YMKB.UI.APIs.Models.NullableOfQuantizationState>(); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("created", Created);
            writer.WriteIntValue("dataCount", DataCount);
            writer.WriteStringValue("fileName", FileName);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("kbId", KbId);
            writer.WriteEnumValue<global::YMKB.UI.APIs.Models.SegmentPattern>("segmentPattern", SegmentPattern);
            writer.WriteLongValue("size", Size);
            writer.WriteEnumValue<global::YMKB.UI.APIs.Models.NullableOfQuantizationState>("status", Status);
            writer.WriteStringValue("type", Type);
            writer.WriteStringValue("url", Url);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
