// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace YMKB.UI.APIs.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum NullableOfQuantizationState
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Loading")]
        #pragma warning disable CS1591
        Loading,
        #pragma warning restore CS1591
        [EnumMember(Value = "Accomplish")]
        #pragma warning disable CS1591
        Accomplish,
        #pragma warning restore CS1591
        [EnumMember(Value = "Fail")]
        #pragma warning disable CS1591
        Fail,
        #pragma warning restore CS1591
    }
}
