// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace YMKB.UI.APIs.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum NullableOfSegmentPattern
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Subsection")]
        #pragma warning disable CS1591
        Subsection,
        #pragma warning restore CS1591
        [EnumMember(Value = "QA")]
        #pragma warning disable CS1591
        QA,
        #pragma warning restore CS1591
    }
}
