// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace YMKB.UI.APIs.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdateQuantizedListCommand : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The kbDocFileId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? KbDocFileId { get; set; }
#nullable restore
#else
        public string KbDocFileId { get; set; }
#endif
        /// <summary>The kbId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? KbId { get; set; }
#nullable restore
#else
        public string KbId { get; set; }
#endif
        /// <summary>The processTime property</summary>
        public DateTimeOffset? ProcessTime { get; set; }
        /// <summary>The remark property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Remark { get; set; }
#nullable restore
#else
        public string Remark { get; set; }
#endif
        /// <summary>The status property</summary>
        public global::YMKB.UI.APIs.Models.QuantizedListState2? Status { get; set; }
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::YMKB.UI.APIs.Models.UpdateQuantizedListCommand"/> and sets the default values.
        /// </summary>
        public UpdateQuantizedListCommand()
        {
            AdditionalData = new Dictionary<string, object>();
            Status = global::YMKB.UI.APIs.Models.QuantizedListState2.Pending;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::YMKB.UI.APIs.Models.UpdateQuantizedListCommand"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::YMKB.UI.APIs.Models.UpdateQuantizedListCommand CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::YMKB.UI.APIs.Models.UpdateQuantizedListCommand();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "id", n => { Id = n.GetStringValue(); } },
                { "kbDocFileId", n => { KbDocFileId = n.GetStringValue(); } },
                { "kbId", n => { KbId = n.GetStringValue(); } },
                { "processTime", n => { ProcessTime = n.GetDateTimeOffsetValue(); } },
                { "remark", n => { Remark = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::YMKB.UI.APIs.Models.QuantizedListState2>(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("kbDocFileId", KbDocFileId);
            writer.WriteStringValue("kbId", KbId);
            writer.WriteDateTimeOffsetValue("processTime", ProcessTime);
            writer.WriteStringValue("remark", Remark);
            writer.WriteEnumValue<global::YMKB.UI.APIs.Models.QuantizedListState2>("status", Status);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
