// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using YMKB.UI.APIs.KnowledgeDbs.Item;
using YMKB.UI.APIs.KnowledgeDbs.Pagination;
using YMKB.UI.APIs.KnowledgeDbs.SearchVectorTest;
using YMKB.UI.APIs.Models;
namespace YMKB.UI.APIs.KnowledgeDbs
{
    /// <summary>
    /// Builds and executes requests for operations under \KnowledgeDbs
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class KnowledgeDbsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The pagination property</summary>
        public global::YMKB.UI.APIs.KnowledgeDbs.Pagination.PaginationRequestBuilder Pagination
        {
            get => new global::YMKB.UI.APIs.KnowledgeDbs.Pagination.PaginationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The SearchVectorTest property</summary>
        public global::YMKB.UI.APIs.KnowledgeDbs.SearchVectorTest.SearchVectorTestRequestBuilder SearchVectorTest
        {
            get => new global::YMKB.UI.APIs.KnowledgeDbs.SearchVectorTest.SearchVectorTestRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the YMKB.UI.APIs.KnowledgeDbs.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::YMKB.UI.APIs.KnowledgeDbs.Item.KnowledgeDbsItemRequestBuilder"/></returns>
        public global::YMKB.UI.APIs.KnowledgeDbs.Item.KnowledgeDbsItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::YMKB.UI.APIs.KnowledgeDbs.Item.KnowledgeDbsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::YMKB.UI.APIs.KnowledgeDbs.KnowledgeDbsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public KnowledgeDbsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/KnowledgeDbs", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::YMKB.UI.APIs.KnowledgeDbs.KnowledgeDbsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public KnowledgeDbsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/KnowledgeDbs", rawUrl)
        {
        }
        /// <summary>
        /// Deletes one or more KnowledgeDbs by their unique IDs.
        /// </summary>
        /// <returns>A <see cref="global::YMKB.UI.APIs.Models.Unit"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::YMKB.UI.APIs.Models.ProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::YMKB.UI.APIs.Models.ProblemDetails">When receiving a 404 status code</exception>
        /// <exception cref="global::YMKB.UI.APIs.Models.HttpValidationProblemDetails">When receiving a 422 status code</exception>
        /// <exception cref="global::YMKB.UI.APIs.Models.ProblemDetails">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::YMKB.UI.APIs.Models.Unit?> DeleteAsync(global::YMKB.UI.APIs.Models.DeleteKnowledgeDbCommand body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::YMKB.UI.APIs.Models.Unit> DeleteAsync(global::YMKB.UI.APIs.Models.DeleteKnowledgeDbCommand body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToDeleteRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::YMKB.UI.APIs.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "404", global::YMKB.UI.APIs.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "422", global::YMKB.UI.APIs.Models.HttpValidationProblemDetails.CreateFromDiscriminatorValue },
                { "500", global::YMKB.UI.APIs.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::YMKB.UI.APIs.Models.Unit>(requestInfo, global::YMKB.UI.APIs.Models.Unit.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a list of all KnowledgeDbs in the system.
        /// </summary>
        /// <returns>A List&lt;global::YMKB.UI.APIs.Models.KnowledgeDbDto&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::YMKB.UI.APIs.Models.ProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::YMKB.UI.APIs.Models.ProblemDetails">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::YMKB.UI.APIs.Models.KnowledgeDbDto>?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::YMKB.UI.APIs.Models.KnowledgeDbDto>> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::YMKB.UI.APIs.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "500", global::YMKB.UI.APIs.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::YMKB.UI.APIs.Models.KnowledgeDbDto>(requestInfo, global::YMKB.UI.APIs.Models.KnowledgeDbDto.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Creates a new KnowledgeDb with the provided details.
        /// </summary>
        /// <returns>A <see cref="string"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::YMKB.UI.APIs.Models.ProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::YMKB.UI.APIs.Models.HttpValidationProblemDetails">When receiving a 422 status code</exception>
        /// <exception cref="global::YMKB.UI.APIs.Models.ProblemDetails">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<string?> PostAsync(global::YMKB.UI.APIs.Models.CreateKnowledgeDbCommand body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<string> PostAsync(global::YMKB.UI.APIs.Models.CreateKnowledgeDbCommand body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::YMKB.UI.APIs.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "422", global::YMKB.UI.APIs.Models.HttpValidationProblemDetails.CreateFromDiscriminatorValue },
                { "500", global::YMKB.UI.APIs.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendPrimitiveAsync<string>(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Updates the details of an existing KnowledgeDb.
        /// </summary>
        /// <returns>A <see cref="global::YMKB.UI.APIs.Models.Unit"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::YMKB.UI.APIs.Models.ProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::YMKB.UI.APIs.Models.ProblemDetails">When receiving a 404 status code</exception>
        /// <exception cref="global::YMKB.UI.APIs.Models.HttpValidationProblemDetails">When receiving a 422 status code</exception>
        /// <exception cref="global::YMKB.UI.APIs.Models.ProblemDetails">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::YMKB.UI.APIs.Models.Unit?> PutAsync(global::YMKB.UI.APIs.Models.UpdateKnowledgeDbCommand body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::YMKB.UI.APIs.Models.Unit> PutAsync(global::YMKB.UI.APIs.Models.UpdateKnowledgeDbCommand body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::YMKB.UI.APIs.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "404", global::YMKB.UI.APIs.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "422", global::YMKB.UI.APIs.Models.HttpValidationProblemDetails.CreateFromDiscriminatorValue },
                { "500", global::YMKB.UI.APIs.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::YMKB.UI.APIs.Models.Unit>(requestInfo, global::YMKB.UI.APIs.Models.Unit.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Deletes one or more KnowledgeDbs by their unique IDs.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(global::YMKB.UI.APIs.Models.DeleteKnowledgeDbCommand body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(global::YMKB.UI.APIs.Models.DeleteKnowledgeDbCommand body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a list of all KnowledgeDbs in the system.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Creates a new KnowledgeDb with the provided details.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::YMKB.UI.APIs.Models.CreateKnowledgeDbCommand body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::YMKB.UI.APIs.Models.CreateKnowledgeDbCommand body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "text/plain;q=0.9");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Updates the details of an existing KnowledgeDb.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::YMKB.UI.APIs.Models.UpdateKnowledgeDbCommand body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::YMKB.UI.APIs.Models.UpdateKnowledgeDbCommand body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::YMKB.UI.APIs.KnowledgeDbs.KnowledgeDbsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::YMKB.UI.APIs.KnowledgeDbs.KnowledgeDbsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::YMKB.UI.APIs.KnowledgeDbs.KnowledgeDbsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class KnowledgeDbsRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class KnowledgeDbsRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class KnowledgeDbsRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class KnowledgeDbsRequestBuilderPutRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
