// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace YMKB.ConsoleTests.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AIModelType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Chat")]
        #pragma warning disable CS1591
        Chat,
        #pragma warning restore CS1591
        [EnumMember(Value = "Embedding")]
        #pragma warning disable CS1591
        Embedding,
        #pragma warning restore CS1591
    }
}
