// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace YMKB.ConsoleTests.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class KbAppDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The answerTokens property</summary>
        public int? AnswerTokens { get; set; }
        /// <summary>The apiFunctionList property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApiFunctionList { get; set; }
#nullable restore
#else
        public string ApiFunctionList { get; set; }
#endif
        /// <summary>The chatModel property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::YMKB.ConsoleTests.Client.Models.AIModelDto2? ChatModel { get; set; }
#nullable restore
#else
        public global::YMKB.ConsoleTests.Client.Models.AIModelDto2 ChatModel { get; set; }
#endif
        /// <summary>The chatModelId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChatModelId { get; set; }
#nullable restore
#else
        public string ChatModelId { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The embeddingModel property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::YMKB.ConsoleTests.Client.Models.AIModelDto2? EmbeddingModel { get; set; }
#nullable restore
#else
        public global::YMKB.ConsoleTests.Client.Models.AIModelDto2 EmbeddingModel { get; set; }
#endif
        /// <summary>The embeddingModelId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EmbeddingModelId { get; set; }
#nullable restore
#else
        public string EmbeddingModelId { get; set; }
#endif
        /// <summary>The icon property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Icon { get; set; }
#nullable restore
#else
        public string Icon { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The kbAppType property</summary>
        public global::YMKB.ConsoleTests.Client.Models.KbAppType? KbAppType { get; set; }
        /// <summary>The kbIdList property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? KbIdList { get; set; }
#nullable restore
#else
        public string KbIdList { get; set; }
#endif
        /// <summary>The maxAskPromptSize property</summary>
        public int? MaxAskPromptSize { get; set; }
        /// <summary>The maxMatchesCount property</summary>
        public int? MaxMatchesCount { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The nativeFunctionList property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NativeFunctionList { get; set; }
#nullable restore
#else
        public string NativeFunctionList { get; set; }
#endif
        /// <summary>The noReplyFoundTemplate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NoReplyFoundTemplate { get; set; }
#nullable restore
#else
        public string NoReplyFoundTemplate { get; set; }
#endif
        /// <summary>The prompt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Prompt { get; set; }
#nullable restore
#else
        public string Prompt { get; set; }
#endif
        /// <summary>The promptTemplate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PromptTemplate { get; set; }
#nullable restore
#else
        public string PromptTemplate { get; set; }
#endif
        /// <summary>The relevance property</summary>
        public double? Relevance { get; set; }
        /// <summary>The temperature property</summary>
        public double? Temperature { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::YMKB.ConsoleTests.Client.Models.KbAppDto"/> and sets the default values.
        /// </summary>
        public KbAppDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::YMKB.ConsoleTests.Client.Models.KbAppDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::YMKB.ConsoleTests.Client.Models.KbAppDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::YMKB.ConsoleTests.Client.Models.KbAppDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "answerTokens", n => { AnswerTokens = n.GetIntValue(); } },
                { "apiFunctionList", n => { ApiFunctionList = n.GetStringValue(); } },
                { "chatModel", n => { ChatModel = n.GetObjectValue<global::YMKB.ConsoleTests.Client.Models.AIModelDto2>(global::YMKB.ConsoleTests.Client.Models.AIModelDto2.CreateFromDiscriminatorValue); } },
                { "chatModelId", n => { ChatModelId = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "embeddingModel", n => { EmbeddingModel = n.GetObjectValue<global::YMKB.ConsoleTests.Client.Models.AIModelDto2>(global::YMKB.ConsoleTests.Client.Models.AIModelDto2.CreateFromDiscriminatorValue); } },
                { "embeddingModelId", n => { EmbeddingModelId = n.GetStringValue(); } },
                { "icon", n => { Icon = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "kbAppType", n => { KbAppType = n.GetEnumValue<global::YMKB.ConsoleTests.Client.Models.KbAppType>(); } },
                { "kbIdList", n => { KbIdList = n.GetStringValue(); } },
                { "maxAskPromptSize", n => { MaxAskPromptSize = n.GetIntValue(); } },
                { "maxMatchesCount", n => { MaxMatchesCount = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "nativeFunctionList", n => { NativeFunctionList = n.GetStringValue(); } },
                { "noReplyFoundTemplate", n => { NoReplyFoundTemplate = n.GetStringValue(); } },
                { "prompt", n => { Prompt = n.GetStringValue(); } },
                { "promptTemplate", n => { PromptTemplate = n.GetStringValue(); } },
                { "relevance", n => { Relevance = n.GetDoubleValue(); } },
                { "temperature", n => { Temperature = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("answerTokens", AnswerTokens);
            writer.WriteStringValue("apiFunctionList", ApiFunctionList);
            writer.WriteObjectValue<global::YMKB.ConsoleTests.Client.Models.AIModelDto2>("chatModel", ChatModel);
            writer.WriteStringValue("chatModelId", ChatModelId);
            writer.WriteStringValue("description", Description);
            writer.WriteObjectValue<global::YMKB.ConsoleTests.Client.Models.AIModelDto2>("embeddingModel", EmbeddingModel);
            writer.WriteStringValue("embeddingModelId", EmbeddingModelId);
            writer.WriteStringValue("icon", Icon);
            writer.WriteStringValue("id", Id);
            writer.WriteEnumValue<global::YMKB.ConsoleTests.Client.Models.KbAppType>("kbAppType", KbAppType);
            writer.WriteStringValue("kbIdList", KbIdList);
            writer.WriteIntValue("maxAskPromptSize", MaxAskPromptSize);
            writer.WriteIntValue("maxMatchesCount", MaxMatchesCount);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("nativeFunctionList", NativeFunctionList);
            writer.WriteStringValue("noReplyFoundTemplate", NoReplyFoundTemplate);
            writer.WriteStringValue("prompt", Prompt);
            writer.WriteStringValue("promptTemplate", PromptTemplate);
            writer.WriteDoubleValue("relevance", Relevance);
            writer.WriteDoubleValue("temperature", Temperature);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
