// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using YMKB.UI.APIs.Models;
namespace YMKB.UI.APIs.KnowledgeDbs.SearchVectorTest
{
    /// <summary>
    /// Builds and executes requests for operations under \KnowledgeDbs\SearchVectorTest
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SearchVectorTestRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::YMKB.UI.APIs.KnowledgeDbs.SearchVectorTest.SearchVectorTestRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SearchVectorTestRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/KnowledgeDbs/SearchVectorTest?kbId={kbId}&search={search}{&minRelevance*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::YMKB.UI.APIs.KnowledgeDbs.SearchVectorTest.SearchVectorTestRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SearchVectorTestRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/KnowledgeDbs/SearchVectorTest?kbId={kbId}&search={search}{&minRelevance*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns a list of KnowledgeDbs matching the search keywords.
        /// </summary>
        /// <returns>A <see cref="global::YMKB.UI.APIs.Models.SearchedVectorsDto"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::YMKB.UI.APIs.Models.ProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::YMKB.UI.APIs.Models.ProblemDetails">When receiving a 404 status code</exception>
        /// <exception cref="global::YMKB.UI.APIs.Models.ProblemDetails">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::YMKB.UI.APIs.Models.SearchedVectorsDto?> GetAsync(Action<RequestConfiguration<global::YMKB.UI.APIs.KnowledgeDbs.SearchVectorTest.SearchVectorTestRequestBuilder.SearchVectorTestRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::YMKB.UI.APIs.Models.SearchedVectorsDto> GetAsync(Action<RequestConfiguration<global::YMKB.UI.APIs.KnowledgeDbs.SearchVectorTest.SearchVectorTestRequestBuilder.SearchVectorTestRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::YMKB.UI.APIs.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "404", global::YMKB.UI.APIs.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "500", global::YMKB.UI.APIs.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::YMKB.UI.APIs.Models.SearchedVectorsDto>(requestInfo, global::YMKB.UI.APIs.Models.SearchedVectorsDto.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a list of KnowledgeDbs matching the search keywords.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::YMKB.UI.APIs.KnowledgeDbs.SearchVectorTest.SearchVectorTestRequestBuilder.SearchVectorTestRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::YMKB.UI.APIs.KnowledgeDbs.SearchVectorTest.SearchVectorTestRequestBuilder.SearchVectorTestRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::YMKB.UI.APIs.KnowledgeDbs.SearchVectorTest.SearchVectorTestRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::YMKB.UI.APIs.KnowledgeDbs.SearchVectorTest.SearchVectorTestRequestBuilder WithUrl(string rawUrl)
        {
            return new global::YMKB.UI.APIs.KnowledgeDbs.SearchVectorTest.SearchVectorTestRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns a list of KnowledgeDbs matching the search keywords.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SearchVectorTestRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("kbId")]
            public string? KbId { get; set; }
#nullable restore
#else
            [QueryParameter("kbId")]
            public string KbId { get; set; }
#endif
            [QueryParameter("minRelevance")]
            public double? MinRelevance { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("search")]
            public string? Search { get; set; }
#nullable restore
#else
            [QueryParameter("search")]
            public string Search { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SearchVectorTestRequestBuilderGetRequestConfiguration : RequestConfiguration<global::YMKB.UI.APIs.KnowledgeDbs.SearchVectorTest.SearchVectorTestRequestBuilder.SearchVectorTestRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
