// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using YMKB.UI.APIs.KbDocFiles.RetryQuantization.Item;
namespace YMKB.UI.APIs.KbDocFiles.RetryQuantization
{
    /// <summary>
    /// Builds and executes requests for operations under \KbDocFiles\retryQuantization
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RetryQuantizationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the YMKB.UI.APIs.KbDocFiles.retryQuantization.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::YMKB.UI.APIs.KbDocFiles.RetryQuantization.Item.RetryQuantizationItemRequestBuilder"/></returns>
        public global::YMKB.UI.APIs.KbDocFiles.RetryQuantization.Item.RetryQuantizationItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::YMKB.UI.APIs.KbDocFiles.RetryQuantization.Item.RetryQuantizationItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::YMKB.UI.APIs.KbDocFiles.RetryQuantization.RetryQuantizationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RetryQuantizationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/KbDocFiles/retryQuantization", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::YMKB.UI.APIs.KbDocFiles.RetryQuantization.RetryQuantizationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RetryQuantizationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/KbDocFiles/retryQuantization", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
