// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using YMKB.ConsoleTests.Client.Auth.Login;
using YMKB.ConsoleTests.Client.Auth.Register;
namespace YMKB.ConsoleTests.Client.Auth
{
    /// <summary>
    /// Builds and executes requests for operations under \Auth
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuthRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The login property</summary>
        public global::YMKB.ConsoleTests.Client.Auth.Login.LoginRequestBuilder Login
        {
            get => new global::YMKB.ConsoleTests.Client.Auth.Login.LoginRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The register property</summary>
        public global::YMKB.ConsoleTests.Client.Auth.Register.RegisterRequestBuilder Register
        {
            get => new global::YMKB.ConsoleTests.Client.Auth.Register.RegisterRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::YMKB.ConsoleTests.Client.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Auth", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::YMKB.ConsoleTests.Client.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Auth", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
